version: '3.8'

services:
    api-server:
        build:
            context: ./api-server
            dockerfile: Dockerfile.prod
        expose:
            - 8000
        env_file: .prod.env
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        environment: 
            - NODE_ENV=production
        expose:
            - 3000

    db:
        image: postgres:alpine
        expose:
            - 5432
        env_file: .prod.env

    reverse-proxy:
        build:
            context: ./reverse-proxy
            dockerfile: Dockerfile.prod
        ports:
            - 8080:80
        depends_on:
            - api-server
            - frontend
