version: '3.8'

services:
    api-server:
        build:
            context: ./api-server
            dockerfile: Dockerfile.dev
        volumes:
            - "./api-server:/code"
        ports:
            - 8000:8000
        env_file: .dev.env

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        environment: 
            - NODE_ENV=development
        volumes:
            - "./frontend:/home/node/code"
        ports:
            - 3000:3000

    db:
        image: postgres:alpine
        ports:
            - 5432:5432
        env_file: .dev.env

    reverse-proxy:
        build:
            context: ./reverse-proxy
            dockerfile: Dockerfile
        ports:
            - 8080:80
