
########## BASE #########

FROM python:3

EXPOSE 8000

########## CONFIGURATION ##########

ENV PYTHONUNBUFFERED 1

COPY . ./code
RUN groupadd -r app && useradd -r -g app app && chown -R app:app ./code
WORKDIR /code
RUN apt-get update && apt-get install -y build-essential python3-dev netcat
RUN pip install -r requirements/prod.txt
RUN chmod u+x entrypoint.sh

ENTRYPOINT [ "/code/entrypoint.sh" ]
CMD uwsgi --ini uwsgi.ini