# Generated by Django 3.1 on 2020-08-25 20:49

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='color',
            field=models.CharField(db_index=True, default='#0000FF', max_length=7, validators=[core.utils.validate_color]),
            preserve_default=False,
        ),
    ]
